#!/bin/bash

if [ -z $1 ]; then
  echo "usage: $0 userName"
  exit
fi;

useradd -G users $1
chmod o+x /home/$1

mkdir /home/$1/.ssh
chmod 700 /home/$1/.ssh
touch /home/$1/.ssh/authorized_keys
chmod 644 /home/$1/.ssh/authorized_keys
chown $1:$1 -R /home/$1/.ssh
chcon -R -t ssh_home_t /home/$1/.ssh;
