#!/bin/bash
# $1 env name
# $2 ServerName
# $3 ServerAlias
# $4 Port
# $5 Websockets
# $6 SSL ("true"/"false"/"both")
# $7 Require
# $8 InternalAlias

PROT="http"
SSLPROXY=""
if [ "$6" == "both" ]; then
  PROT="https"
  SSLPROXY="SSLProxyEngine on
  SSLProxyVerify none
  SSLProxyCheckPeerCN off
  SSLProxyCheckPeerName off"
fi

if [ "$6" == "true" ] || [ "$6" == "both" ] ; then
  echo "<VirtualHost *:80>
  ServerName $2
  ServerAlias $3

  Redirect / https://$2/
</VirtualHost>
<VirtualHost *:443>
  ServerName $2
  ServerAlias $3

  Include /etc/httpd/conf.d/shared/ssl.conf

  ProxyPreserveHost On
  $SSLPROXY
  $5
  ProxyPass        / $PROT://127.0.0.1:$4/$8 timeout=300
  ProxyPassReverse / $PROT://127.0.0.1:$4/$8
  <Proxy *>
    Require $7
  </Proxy>
</VirtualHost>" > /etc/httpd/conf.d/sites-enabled/$1.conf
else
  echo "<VirtualHost *:80>
  ServerName $2
  ServerAlias $3

  ProxyPreserveHost On
  $5
  ProxyPass        / $PROT://127.0.0.1:$4/$8 timeout=300
  ProxyPassReverse / $PROT://127.0.0.1:$4/$8
  <Proxy *>
    Require $7
  </Proxy>
</VirtualHost>" > /etc/httpd/conf.d/sites-enabled/$1.conf

fi
systemctl reload httpd
