#!/bin/bash
# why to /usr/lib/systemd ???
echo "[Unit]
Description=$1
Requires=docker.service
After=docker.service

[Service]
Restart=always
ExecStart=/usr/bin/docker start -a $1
ExecStop=/usr/bin/docker stop $1

[Install]
WantedBy=multi-user.target" > /usr/lib/systemd/system/docker-${1}.service
systemctl daemon-reload
systemctl enable docker-${1}.service

