#!/bin/bash

if [ -z $1 ]; then
  echo "usage: $0 userName"
  exit
fi;

useradd -G users $1
chmod o+x /home/$1
# for environment development
# usermod -g users $1
# chgrp -R users /home/$1
# chmod g+rwx /home/$1

# ssh
mkdir /home/$1/.ssh
chmod 700 /home/$1/.ssh
touch /home/$1/.ssh/authorized_keys
chmod 600 /home/$1/.ssh/authorized_keys
chown $1:$1 -R /home/$1/.ssh
chcon -R -t ssh_home_t /home/$1/.ssh;

# quota
uid=`id -u $1`
grep -v $1 /etc/projects > /tmp/projects; mv /tmp/projects /etc/projects && echo "$uid:/home/$1" >> /etc/projects
grep -v $1 /etc/projid > /tmp/projid; mv /tmp/projid /etc/projid && echo "$1:$uid" >> /etc/projid
xfs_quota -x -c "project -s $1" /home > /dev/null
xfs_quota -x -c "limit -p bsoft=1000m bhard=1500m $1" /home > /dev/null
docker-check-quota
