#!/bin/bash
if [ "$1" != "" ]; then
	cd $1 && \
	git checkout master && \
	git pull origin master && \
	python setup.py build && python setup.py install
else
	cd /tmp && \
	git clone https://redmine.acdh.oeaw.ac.at/docker-tools.git && \
	cd docker-tools && \
	python setup.py build && python setup.py install && \
	cd .. && \
	rm -fR docker-tools
fi
