#!/bin/bash

if [ -z $1 ]; then
	echo "usage: $0 accountName"
	exit
fi

# apache
echo 'Removing Apache proxy config...'
rm -f /etc/httpd/conf.d/sites-enabled/$1*.conf

# systemd
echo 'Removing systemd startup scripts...'
for i in `ls -1 /usr/lib/systemd/system/docker-${1}-*.service`; do
	rm -f $i
done
for i in `find /etc/systemd/system -name docker-${1}*.service`; do
	rm -f $i
done

# docker
echo 'Stoping and removing docker containers...'
for i in `docker ps -f name=${1}-* -q`; do
	docker rm -fv $i
done
docker-remove-unused-containers
docker-remove-unused-images > /dev/null 2>&1

# /srv/docker
echo 'Removing symbolic links under /srv/docker/...'
rm -fR /srv/docker/${1}-*

echo 'Recreating configured environments...'
