#!/bin/bash

if [ -z $1 ]; then
  echo "usage: $0 userName"
  exit
fi;

uid=`id -u $1`
sed -i "/:$uid/d" /etc/projid
sed -i "/$uid:/d" /etc/projects

echo '[]' > /home/$1/config.json
docker-manage-admin -p $1

userdel -r $1
