#!/bin/bash

sed -i -e 's/dockerroot/docker/' /etc/group
sed -e -e 's/home +xfs +defaults /home +xfs +defaults,pquota /' /etc/fstab

# to enable volumes access for normal users
chmod +x /var/lib/docker
chmod 777 /var/lib/docker/images/tmp

# SELinux context to allow docker access external mounts
semanage fcontext -a -t svirt_sandbox_file_t "/home(/.*)?"
restorecon -RvF /home

# As apache is the reverse proxy it has to be able to connect
# via network
setsebool -P httpd_can_network_connect true
