#!/bin/bash

cat import.py IEnvironment.py HTTPReverseProxy.py Param.py Configuration.py Account.py Environments/Environment.py Environments/EnvironmentHTTP.py Environments/EnvironmentApache.py Environments/EnvironmentPHP.py Environments/EnvironmentDrupal7.py Environments/EnvironmentWSGI3.py Environments/EnvironmentWSGI2.py Environments/EnvironmentNoske.py Environments/EnvironmentJava8.py Environments/EnvironmentExistdb30.py Environments/Environmentcrxqmets.py main.py > ../docker-manage-admin
chmod +x ../docker-manage-admin
cp -f ../docker-manage-admin /usr/sbin/docker-manage-admin

