#!/bin/bash
echo "[Unit]
Description=$1
Requires=docker.service
After=docker.service

[Service]
Restart=on-failure
ExecStart=/usr/bin/docker start -a $1
ExecStop=/usr/bin/docker stop $1

[Install]
WantedBy=multi-user.target" > /etc/systemd/system/docker-${1}.service
systemctl daemon-reload
systemctl disable docker-${1}.service
systemctl enable docker-${1}.service

