#!/bin/bash

if [ -z $1 ]; then
	echo "usage: $0 environmentName"
	exit
fi

# apache
echo 'Removing Apache proxy config...'
rm -f /etc/httpd/conf.d/sites-enabled/$1.conf

# docker
echo 'Stoping and removing docker containers...'
docker stop $1 -t 60
docker rm -fv $1
docker-remove-unused-containers
docker-remove-unused-images > /dev/null 2>&1

